### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by Norman191** [mr0kaushik/ChattingApp#2]
App crashes here : 
in the **_UsersFragment.java_**

     for (DataSnapshot snapshot : dataSnapshot.getChildren()) {
                        User user = snapshot.getValue(User.class);
                        assert user != null;
                        assert firebaseUser != null;
                        if (!user.getId().equals(firebaseUser.getUid())) {
                            userList.add(user);
                        }
                    }

Error =
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at chatfree.com.Fragments.UsersFragment$3.onDataChange(UsersFragment.java:124)

**Comment by mr0kaushik** [comment]
Have done some changes in the [raw file](https://github.com/mr0kaushik/ChattingApp/commit/d7b17dc508b611ac9ef3175b6318e7390351f51b#diff-5f53a414e826e23753a7eb901c31a8c9) i hope it will help, Well i m currently not working on it, so it is difficult to add features and make changes.
